fastlane_version "2.38.1"

default_platform :android

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "check assembleBeta")
    crashlytics
  end

  desc "Build new beta version App"
  lane :buildBeta do
    gradle(task: "assembleBeta")
  end

  after_all do |lane|
    case lane
    when :beta
        slack(message: "Successfully deployed new App Update.")
    end
  end

  error do |lane, exception|
    slack(
      message: exception.message,
      success: false
    )
  end
end